<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZ9dOWP\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZ9dOWP/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerMZ9dOWP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerMZ9dOWP\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerMZ9dOWP\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'MZ9dOWP',
    'container.build_id' => '07617faa',
    'container.build_time' => 1636739251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZ9dOWP');
