<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFeaIRqY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFeaIRqY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFeaIRqY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFeaIRqY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFeaIRqY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FeaIRqY',
    'container.build_id' => '7bbc50a1',
    'container.build_time' => 1637434468,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFeaIRqY');
