<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIP3b8pR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIP3b8pR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIP3b8pR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIP3b8pR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIP3b8pR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IP3b8pR',
    'container.build_id' => 'facd8e52',
    'container.build_time' => 1637175466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIP3b8pR');
