<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container15pmxjb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container15pmxjb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container15pmxjb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container15pmxjb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container15pmxjb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '15pmxjb',
    'container.build_id' => 'b40d7ed7',
    'container.build_time' => 1636812794,
], __DIR__.\DIRECTORY_SEPARATOR.'Container15pmxjb');
